// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSLVD9YTuNvHS9TiUO7p_YObM0cjWJFq8',
    appId: '1:1061067137357:web:212886e2ecc2906e569704',
    messagingSenderId: '1061067137357',
    projectId: 'vocabulary-battle-01',
    authDomain: 'vocabulary-battle-01.firebaseapp.com',
    databaseURL: 'https://vocabulary-battle-01-default-rtdb.firebaseio.com',
    storageBucket: 'vocabulary-battle-01.firebasestorage.app',
    measurementId: 'G-HMK0M189K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkW0GKfx9EACMwkua7Uk6bz1gMYkFmueg',
    appId: '1:1061067137357:android:0390b2a654626881569704',
    messagingSenderId: '1061067137357',
    projectId: 'vocabulary-battle-01',
    databaseURL: 'https://vocabulary-battle-01-default-rtdb.firebaseio.com',
    storageBucket: 'vocabulary-battle-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbzZBLRyJrcwIot8IU9fGsJzXolqQG8Ss',
    appId: '1:1061067137357:ios:fc8c3a52c620c014569704',
    messagingSenderId: '1061067137357',
    projectId: 'vocabulary-battle-01',
    databaseURL: 'https://vocabulary-battle-01-default-rtdb.firebaseio.com',
    storageBucket: 'vocabulary-battle-01.firebasestorage.app',
    androidClientId:
        '1061067137357-0sp5s6fhcp5lu1jvrhh2rumomnb62id4.apps.googleusercontent.com',
    iosClientId:
        '1061067137357-j65j9jak4j5h9mgo2v52c4thtr9e5au9.apps.googleusercontent.com',
    iosBundleId: 'com.example.vocabularyBattleAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbzZBLRyJrcwIot8IU9fGsJzXolqQG8Ss',
    appId: '1:1061067137357:ios:fc8c3a52c620c014569704',
    messagingSenderId: '1061067137357',
    projectId: 'vocabulary-battle-01',
    databaseURL: 'https://vocabulary-battle-01-default-rtdb.firebaseio.com',
    storageBucket: 'vocabulary-battle-01.firebasestorage.app',
    androidClientId:
        '1061067137357-0sp5s6fhcp5lu1jvrhh2rumomnb62id4.apps.googleusercontent.com',
    iosClientId:
        '1061067137357-j65j9jak4j5h9mgo2v52c4thtr9e5au9.apps.googleusercontent.com',
    iosBundleId: 'com.example.vocabularyBattleAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSLVD9YTuNvHS9TiUO7p_YObM0cjWJFq8',
    appId: '1:1061067137357:web:7636d77cdad68548569704',
    messagingSenderId: '1061067137357',
    projectId: 'vocabulary-battle-01',
    authDomain: 'vocabulary-battle-01.firebaseapp.com',
    databaseURL: 'https://vocabulary-battle-01-default-rtdb.firebaseio.com',
    storageBucket: 'vocabulary-battle-01.firebasestorage.app',
    measurementId: 'G-LR9W6EL8YL',
  );
}
